"""Pydantic Schemas for API validation"""
from app.schemas.user import (
    KdfParams,
    EncryptedBlob,
    ZKRegisterRequest,
    ZKLoginChallengeRequest,
    ZKLoginChallengeResponse,
    ZKLoginVerifyRequest,
    UserResponse,
    CurrentUserResponse,
    SessionResponse,
    ChangePasswordRequest,
    UpdateProfileRequest,
    UpdateAuthKeyRequest,
    CsrfTokenResponse,
    SessionDeviceItem,
    SessionListResponse,
    RevokeSessionsRequest,
    RevokeSessionsResponse,
)
from app.schemas.file import (
    FileUploadMetadata,
    FileUploadResponse,
    StorageUsageResponse,
    FileListItem,
    FileListResponse,
    FileDeleteResponse,
    FileUploadSessionCreateRequest,
    FileUploadSessionResponse,
    FileUploadPartResponse,
    FileUploadCompleteRequest,
    FileUploadAbortResponse,
)
from app.schemas.sharing import (
    UserPublicInfo,
    UserSearchResponse,
    DeviceShareEnvelopeRequest,
    ShareFileRequest,
    ShareFileResponse,
    SharedFileInfo,
    SharedWithMeResponse,
    SharedByMeResponse,
    FileShareInfo,
    FileSharesResponse,
    UnshareResponse,
    UpdateKeypairRequest,
    DeviceKeyInfo,
    DeviceKeyCreateRequest,
    DeviceKeyListResponse,
    DeviceKeyRevokeResponse,
    ShareEnvelopeInfo,
    StrongRevokeResponse,
    RotateRecipientEnvelope,
    RotateFileContentMetadata,
    RotateFileContentResponse,
)
from app.schemas.mfa import (
    MFASetupRequest,
    MFASetupResponse,
    MFAStatusResponse,
    MFAVerifyRequest,
    MFAVerifyResponse,
    MFADisableRequest,
    MFADisableResponse,
    MFALoginChallengeResponse,
)
from app.schemas.folder import (
    FolderCreateRequest,
    FolderResponse,
    FolderListResponse,
    FolderRenameRequest,
    FolderMoveRequest,
)
from app.schemas.audit import (
    AuditLogItem,
    AuditListResponse,
    AuditIntegrityResponse,
)
from app.schemas.link import (
    CreateLinkRequest,
    LinkResponse,
    LinkPublicInfo,
    VerifyLinkPasswordRequest,
    VerifyLinkPasswordResponse,
    LinkListResponse,
)
from app.schemas.recovery import (
    RecoverySetupRequest,
    RecoverySetupResponse,
    RecoveryStatusResponse,
    RecoveryChallengeRequest,
    RecoveryChallengeResponse,
    RecoveryResetRequest,
    RecoveryResetResponse,
)

__all__ = [
    # Auth schemas
    "KdfParams",
    "EncryptedBlob",
    "ZKRegisterRequest",
    "ZKLoginChallengeRequest",
    "ZKLoginChallengeResponse",
    "ZKLoginVerifyRequest",
    "UserResponse",
    "CurrentUserResponse",
    "SessionResponse",
    "UpdateProfileRequest",
    "UpdateAuthKeyRequest",
    "CsrfTokenResponse",
    "SessionDeviceItem",
    "SessionListResponse",
    "RevokeSessionsRequest",
    "RevokeSessionsResponse",
    # File schemas
    "FileUploadMetadata",
    "FileUploadResponse",
    "StorageUsageResponse",
    "FileListItem",
    "FileListResponse",
    "FileDeleteResponse",
    "FileUploadSessionCreateRequest",
    "FileUploadSessionResponse",
    "FileUploadPartResponse",
    "FileUploadCompleteRequest",
    "FileUploadAbortResponse",
    # Sharing schemas
    "UserPublicInfo",
    "UserSearchResponse",
    "DeviceShareEnvelopeRequest",
    "ShareFileRequest",
    "ShareFileResponse",
    "SharedFileInfo",
    "SharedWithMeResponse",
    "SharedByMeResponse",
    "FileShareInfo",
    "FileSharesResponse",
    "UnshareResponse",
    "UpdateKeypairRequest",
    "DeviceKeyInfo",
    "DeviceKeyCreateRequest",
    "DeviceKeyListResponse",
    "DeviceKeyRevokeResponse",
    "ShareEnvelopeInfo",
    "StrongRevokeResponse",
    "RotateRecipientEnvelope",
    "RotateFileContentMetadata",
    "RotateFileContentResponse",
    # MFA schemas
    "MFASetupRequest",
    "MFASetupResponse",
    "MFAStatusResponse",
    "MFAVerifyRequest",
    "MFAVerifyResponse",
    "MFADisableRequest",
    "MFADisableResponse",
    "MFALoginChallengeResponse",
    # Folder schemas
    "FolderCreateRequest",
    "FolderResponse",
    "FolderListResponse",
    "FolderRenameRequest",
    "FolderMoveRequest",
    # Audit schemas
    "AuditLogItem",
    "AuditListResponse",
    "AuditIntegrityResponse",
    # Link schemas
    "CreateLinkRequest",
    "LinkResponse",
    "LinkPublicInfo",
    "VerifyLinkPasswordRequest",
    "VerifyLinkPasswordResponse",
    "LinkListResponse",
    # Recovery schemas
    "RecoverySetupRequest",
    "RecoverySetupResponse",
    "RecoveryStatusResponse",
    "RecoveryChallengeRequest",
    "RecoveryChallengeResponse",
    "RecoveryResetRequest",
    "RecoveryResetResponse",
]
